name: "Deployment (preview)"

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  preview:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    env:
      SERVER_ENV: staging
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      # `pnpm build` is not required because it runs on `prepare` process

      - name: "[preview] deploy Cloudflare Worker"
        id: preview
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0.0
        with:
          command: versions upload --message "Branch - ${{ github.ref_name }}"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: "[preview] Add comment for deployment URL"
        run: "gh pr comment ${{ github.event.number }} --edit-last --create-if-none --body 'Deployed to preview:\n${{ steps.preview.outputs.pages-deployment-alias-url && steps.preview.outputs.pages-deployment-alias-url || steps.preview.outputs.deployment-url }}'"
        env:
          GH_TOKEN: ${{ github.token }}
