name: "Deployment (production)"

on:
  push:
    branches:
      - main
  repository_dispatch:
    types:
      - langdata-update

permissions:
  contents: read
  pull-requests: write

jobs:
  release:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      SERVER_ENV: production
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      # `pnpm build` is not required because it runs on `prepare` process

      - name: "[production] deploy Cloudflare Worker"
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
