name: "Purge cache of Cloudflare CDN"

on:
  check_run:
    types:
      - completed

permissions:
  contents: read

env:
  SERVER_ENV: development

jobs:
  trigger:
    if: ${{ github.event.check_run.name == 'Cloudflare Pages' && github.event.check_run.conclusion == 'success' && github.event.check_run.head_sha == github.sha && github.ref == 'refs/heads/main' && github.repository_owner == 'xicri' }}
    timeout-minutes: 3
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pnpm/action-setup@08c4be7e2e672a47d11bd04269e27e5f3e8529cb # v6.0.0
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24
          cache: pnpm

      - name: Purge cache of Cloudflare CDN
        run: |
          pnpm install jiti undici
          pnpm purge-cache
