name: "Purge cache of Cloudflare CDN"

on:
  check_run:
    types:
      - completed

permissions:
  contents: read

env:
  SERVER_ENV: development

jobs:
  trigger:
    if: ${{ github.event.check_run.name == 'Cloudflare Pages' && github.event.check_run.conclusion == 'success' && github.event.check_run.head_sha == github.sha && github.ref == 'refs/heads/main' && github.repository_owner == 'xicri' }}
    timeout-minutes: 3
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24
          cache: pnpm

      - name: Purge cache of Cloudflare CDN
        run: |
          pnpm install jiti undici
          pnpm purge-cache
