name: "VRT"

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  vrt:
    timeout-minutes: 15
    env:
      SERVER_ENV: development
      AWS_REGION: auto # Cloudflare R2's region should be `auto`.
      AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
      REG_SUIT_GITHUB_CLIENT_ID: ${{ secrets.REG_SUIT_GITHUB_CLIENT_ID }}
      HASH_PR: ${{ github.event.pull_request.head.sha }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # See: https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: pnpm/action-setup@08c4be7e2e672a47d11bd04269e27e5f3e8529cb # v6.0.0
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24
          cache: pnpm

      - name: cache playwright browsers
        id: playwright-cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.cache/ms-playwright
          key: playwright

      - name: Cache deb files
        id: deb-cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: /var/cache/apt/archives
          # To avoid keeping caches of too old deb files,
          # refresh it when the lock file is updated
          key: deb-${{ hashFiles('**/pnpm-lock.yaml') }}

      - run: pnpm install --frozen-lockfile
      - name: Install browsers & system deps for Playwright
        run: pnpm e2e:prepare
      - run: pnpm build
      - run: pnpm vrt
