name: "VRT"

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  vrt:
    timeout-minutes: 15
    env:
      SERVER_ENV: development
      AWS_REGION: auto # Cloudflare R2's region should be `auto`.
      AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
      REG_SUIT_GITHUB_CLIENT_ID: ${{ secrets.REG_SUIT_GITHUB_CLIENT_ID }}
      HASH_PR: ${{ github.event.pull_request.head.sha }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          # See: https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24
          cache: pnpm

      - name: cache playwright browsers
        id: playwright-cache
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: ~/.cache/ms-playwright
          key: playwright

      - name: Cache deb files
        id: deb-cache
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: /var/cache/apt/archives
          # To avoid keeping caches of too old deb files,
          # refresh it when the lock file is updated
          key: deb-${{ hashFiles('**/pnpm-lock.yaml') }}

      - run: pnpm install --frozen-lockfile
      - name: Install browsers & system deps for Playwright
        run: pnpm e2e:prepare
      - run: pnpm build
      - run: pnpm vrt
